print("******************************************************")
print("* Calculadora simple en Python                       *")
print("* Ingrese dos números para realizar operaciones:     *")
a = float(input("* Primer número: "))
b = float(input("* Segundo número: "))
print("* El resultado de las operaciones es: ",            "*")
print("* Suma: "            , a + b,                       "*")
print("* Resta: "           , a - b,                       "*") 
print("* Multiplicación: "  , a * b,                       "*")
print("* División: "        , a / b,                       "*")
print("******************************************************")